version: '3.1'

services:
  postgres:
    image: postgres:14
    restart: always
    env_file: .env
    ports: 
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - catalog-network
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3000
    expose:
      - 3333
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - catalog-network
volumes:
  db:
    driver: local
networks:
  catalog-network:
    name: 'catalog-network'