version: '3.1'

services:
  postgres:
    image: postgres:14
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - catalog
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - postgres
    networks:
      - catalog
volumes:
  db:
    driver: local
networks:
  catalog:
    driver: bridge
